theme: jekyll-theme-minimal
github:
  is_project_page: false
avatar: "https://media-exp1.licdn.com/dms/image/C4E03AQEcoBQSUAEAMw/profile-displayphoto-shrink_800_800/0/1613662973953?e=1632355200&v=beta&t=nb_wmf1IS43fH7hqrLXnCvNHzrb7PuOhn5A5o-UFJt0"
round-avatar: true
